Added Release-enforcment

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -3,6 +3,25 @@ description: Utilized for creating releases of projects
 
 # Inputs
 inputs:
+  nexus_repo_id:
+    description: "Nexus Repository ID" 
+    required: false
+    default: "maven-snapshots"
+  nexus_repo_username:
+    description: "Nexus Repository Username" 
+    required: false 
+    default: "admin"
+  is_tag:
+    description: "Check if running on tag"
+    required: false
+    default: 'false'
+  nexus_repo_password:
+    description: "Nexus Repository Password"  
+    required: true
+  nexus_repo_url:
+    description: "Nexus Repository URL"
+    required: false 
+    default: "https://nexus.tinkarbuild.com" 
   github_token:
     description: "GitHub Token"
     required: true
@@ -18,14 +37,22 @@ inputs:
   ossrh_token:
     description: "OSSRH Token"
     required: true
+  branch_name: 
+    description: "Branch Name" 
+    required: true 
+
+outputs:
+  release_upload_url:
+    description: "Release Url"
+    value: ${{ steps.create_release.outputs.upload_url }}
+  is_snapshot_version:
+     description: "Is Snapshot Version"
+     value: ${{ steps.is_snapshot.outputs.IS_SNAPSHOT_VERSION }}
 
 
 runs:
   using: "composite"
   steps:
-     - name: Checkout Repository
-       uses: actions/checkout@v4
-    
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
@@ -37,6 +64,37 @@ runs:
             gpg-private-key: ${{inputs.gpg_key}}
             gpg-passphrase: MAVEN_GPG_PASSPHRASE
 
+     - name: Extract Version
+       id: get_current_version
+       shell: bash
+       run: |
+          echo "POM_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
+
+     - name: Check if IS_SNAPSHOT
+       id: is_snapshot
+       shell: bash
+       run: |
+            echo "IS_SNAPSHOT_VERSION=$IS_SNAPSHOT" >> $GITHUB_OUTPUT
+            if [ $IS_SNAPSHOT == 'true' ]; then
+             echo "NEXUS_REPO_ID=maven-snapshots">> $GITHUB_OUTPUT
+            elif [ $IS_SNAPSHOT == 'false' ]; then
+             echo "NEXUS_REPO_ID=maven-releases">> $GITHUB_OUTPUT
+            else
+             echo "ERROR: Incorrect Type $IS_SNAPSHOT"
+             exit 1
+            fi
+       env:
+         IS_SNAPSHOT:  ${{ contains(steps.get_current_version.outputs.POM_VERSION, '-SNAPSHOT')}}
+       
+
+     - name: Maven Settings File
+       uses: whelk-io/maven-settings-xml-action@v22
+       with:
+        servers: '[{"id": "${{ steps.is_snapshot.outputs.NEXUS_REPO_ID }}", "username": "${{inputs.nexus_repo_username}}", "password": "${{inputs.nexus_repo_password}}"}]'
+        profiles: '[{"id": "${{inputs.nexus_profile}}", "properties": {"altDeploymentRepository": "${{  steps.is_snapshot.outputs.NEXUS_REPO_ID  }}::${{ inputs.nexus_repo_url }}/repository/${{ steps.is_snapshot.outputs.NEXUS_REPO_ID  }}"}}]'
+        active_profiles: '["${{inputs.nexus_profile}}"]' 
+        output_file: .m2/settings.xml
+
      - name: Maven Build
        shell: bash
        run: |
@@ -45,10 +103,24 @@ runs:
             -e \
             -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
             -Dmaven.build.cache.enabled=false \
-            -Prelease-enforcement
+            -Prelease-enforcment
+
+     - name: Deploy To Nexus
+       shell: bash
+       if: github.event.repository.name != 'jpms-deps'
+       run: |
+          ./mvnw deploy \
+            --batch-mode \
+            -e \
+            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
+            -DskipTests \
+            -DskipITs \
+            -s '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml'\
+            -DrepositoryId='${{ steps.is_snapshot.outputs.NEXUS_REPO_ID  }}'
     
      - name: Publish To OSSRH (Maven Central Staging)
        shell: bash
+       if: steps.is_snapshot.outputs.IS_SNAPSHOT_VERSION == 'false' && github.event.repository.name != 'komet_test'
        run: |
             ./mvnw deploy -U\
                   --batch-mode \
@@ -69,12 +141,17 @@ runs:
           MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg_passphrase }}
 
      - name: Create Release
-       shell: bash
-       run: |
-              curl -L \
-                -X POST \
-                -H "Accept: application/vnd.github+json" \
-                -H "Authorization: Bearer ${{inputs.github_token}}" \
-                -H "X-GitHub-Api-Version: 2022-11-28" \
-                  https://api.github.com/repos/${{github.repository}}/releases \
-                -d '{"tag_name":"${{github.ref_name}}","name":"Release ${{github.ref_name}}","body":"Release ${{github.ref_name}}","draft":false,"prerelease":false,"generate_release_notes":false}'
+       id: create_release
+       if: steps.is_snapshot.outputs.IS_SNAPSHOT_VERSION == 'false'
+       uses: comnoco/create-release-action@v2.0.5
+       env:
+          GITHUB_TOKEN: ${{ inputs.github_token }}
+       with:
+          tag_name: ${{ inputs.branch_name }}
+          release_name: Release ${{ inputs.branch_name }}
+          body: |
+            Release ${{ inputs.branch_name }}
+          draft: false
+          prerelease: false
+
+     
